name: Sync
'on':
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '* 12 * * *'
jobs:
  secrets:
    name: Sync queries from upstream.
    runs-on: ubuntu-latest
    steps:
      - uses: adrianjost/files-sync-action@master
        with:
          COMMIT_MESSAGE: Sync queries from upstream.
          SRC_REPO: |-
            nvim-treesitter/nvim-treesitter-textobjects:main
          SRC_ROOT: /queries/
          FILE_PATTERNS: |-
            ^.*\.scm$
          TARGET_REPOS: |-
            gh-liu/nvim-treesitter-textobjects
          TARGET_ROOT: /queries/
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
